services:
  # Spring Boot Web Service
  - type: web
    name: myapp-backend
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d6g15adm5p6s7393jh0g-a.oregon-postgres.render.com:5432/myapp_1vxx
      - key: SPRING_DATASOURCE_USERNAME
        value: myapp_1vxx_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: BTUEi0O5iR7litF5365MvJV9USj0V0LC
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
